### ISSUE TITLE
Is it possible to not Zoom to the left? 

### ISSUE THREAD

**Issue by redapplewithleaves** [viewthespace/angular-zoom-directive#1]
Hello,

Great job on this directive! It was what I've been looking for a while now: To Zoom into Dom elements instead of images. 

I have a menu on the left hand side of the page, and I would like to "Zoom In" that would not grow the DOM element to the left. I tried adding margin, but it didn't quite work out as I wanted it to. 

Is it possible to not Zoom to the left? 

http://plnkr.co/edit/yEkefGElsMm3bTuBORUN?p=preview

**Comment by redapplewithleaves** [comment]
Ah, Nevermind! I found it. 

I changed transformOrigin to 'left top' and that did the trick.

Thanks again for a great directive.

**Comment by shaw3257** [comment]
Thanks @redapplewithleaves !
