### ISSUE TITLE
Incompatible with Firefox?

### ISSUE THREAD

**Issue by redapplewithleaves** [viewthespace/angular-zoom-directive#2]
Hello,

All this time I've been using Chrome browser and it has been working out great.
However, today, I tried using Firefox and I got the following error:

Error: x is not defined
calculateSteps@http://10.5.14.115:8080/ngModules/angular-zoom-directive.js:124:29
.link/<@http://10.5.14.115:8080/ngModules/angular-zoom-directive.js:98:38
f/k<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:138:46
e@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:40:72
lf/m.defer/c<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:44:72

Any ideas on how to fix this?

**Comment by shaw3257** [comment]
Hey @redapplewithleaves, I'll take a look tonight if I have some time. Thanks for reporting!

**Comment by shaw3257** [comment]
Looks like there was an issue with firefox. v1.0.5 should fix it.

**Comment by redapplewithleaves** [comment]
Awesome! It is fixed :D

Thanks!
